using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class GiantCritModel
{
    [RealtimeProperty(1, true, true)] int _critCount;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class GiantCritModel : RealtimeModel {
    public int critCount {
        get {
            return _critCountProperty.value;
        }
        set {
            if (_critCountProperty.value == value) return;
            _critCountProperty.value = value;
            InvalidateReliableLength();
            FireCritCountDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(GiantCritModel model, T value);
    public event PropertyChangedHandler<int> critCountDidChange;
    
    public enum PropertyID : uint {
        CritCount = 1,
    }
    
    #region Properties
    
    private ReliableProperty<int> _critCountProperty;
    
    #endregion
    
    public GiantCritModel() : base(null) {
        _critCountProperty = new ReliableProperty<int>(1, _critCount);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _critCountProperty.UnsubscribeCallback();
    }
    
    private void FireCritCountDidChange(int value) {
        try {
            critCountDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _critCountProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _critCountProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.CritCount: {
                    changed = _critCountProperty.Read(stream, context);
                    if (changed) FireCritCountDidChange(critCount);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _critCount = critCount;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
