using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class PlayerDataModel 
{
    [RealtimeProperty(1, true, true)] bool _isDead;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class PlayerDataModel : RealtimeModel {
    public bool isDead {
        get {
            return _isDeadProperty.value;
        }
        set {
            if (_isDeadProperty.value == value) return;
            _isDeadProperty.value = value;
            InvalidateReliableLength();
            FireIsDeadDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(PlayerDataModel model, T value);
    public event PropertyChangedHandler<bool> isDeadDidChange;
    
    public enum PropertyID : uint {
        IsDead = 1,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _isDeadProperty;
    
    #endregion
    
    public PlayerDataModel() : base(null) {
        _isDeadProperty = new ReliableProperty<bool>(1, _isDead);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _isDeadProperty.UnsubscribeCallback();
    }
    
    private void FireIsDeadDidChange(bool value) {
        try {
            isDeadDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _isDeadProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _isDeadProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.IsDead: {
                    changed = _isDeadProperty.Read(stream, context);
                    if (changed) FireIsDeadDidChange(isDead);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _isDead = isDead;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
