using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class StaffModel 
{
    [RealtimeProperty(1, true, true)] bool _slowGiant;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class StaffModel : RealtimeModel {
    public bool slowGiant {
        get {
            return _slowGiantProperty.value;
        }
        set {
            if (_slowGiantProperty.value == value) return;
            _slowGiantProperty.value = value;
            InvalidateReliableLength();
            FireSlowGiantDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(StaffModel model, T value);
    public event PropertyChangedHandler<bool> slowGiantDidChange;
    
    public enum PropertyID : uint {
        SlowGiant = 1,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _slowGiantProperty;
    
    #endregion
    
    public StaffModel() : base(null) {
        _slowGiantProperty = new ReliableProperty<bool>(1, _slowGiant);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _slowGiantProperty.UnsubscribeCallback();
    }
    
    private void FireSlowGiantDidChange(bool value) {
        try {
            slowGiantDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _slowGiantProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _slowGiantProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.SlowGiant: {
                    changed = _slowGiantProperty.Read(stream, context);
                    if (changed) FireSlowGiantDidChange(slowGiant);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _slowGiant = slowGiant;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
