using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class TutorialModel 
{
    [RealtimeProperty(1, true, true)] int _tutorialHit;

}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class TutorialModel : RealtimeModel {
    public int tutorialHit {
        get {
            return _tutorialHitProperty.value;
        }
        set {
            if (_tutorialHitProperty.value == value) return;
            _tutorialHitProperty.value = value;
            InvalidateReliableLength();
            FireTutorialHitDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(TutorialModel model, T value);
    public event PropertyChangedHandler<int> tutorialHitDidChange;
    
    public enum PropertyID : uint {
        TutorialHit = 1,
    }
    
    #region Properties
    
    private ReliableProperty<int> _tutorialHitProperty;
    
    #endregion
    
    public TutorialModel() : base(null) {
        _tutorialHitProperty = new ReliableProperty<int>(1, _tutorialHit);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _tutorialHitProperty.UnsubscribeCallback();
    }
    
    private void FireTutorialHitDidChange(int value) {
        try {
            tutorialHitDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _tutorialHitProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _tutorialHitProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.TutorialHit: {
                    changed = _tutorialHitProperty.Read(stream, context);
                    if (changed) FireTutorialHitDidChange(tutorialHit);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _tutorialHit = tutorialHit;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
